name: C/C++ CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: make structure
      run: make structure OS=LIN
    - name: make ping
      run: make ping OS=LIN
    - name: make keygen
      run: make keygen OS=LIN
    - name: download gmock
      run: |
        mkdir -p ./gmock/
        curl https://codeload.github.com/google/googletest/zip/refs/tags/release-1.10.0 -o ./gmock/googletest-release-1.10.0.zip
        unzip ./gmock/googletest-release-1.10.0.zip
        ls
    - name: install gmock
      run: make install_gmock GMOCK_ROOT=./gmock/googletest-release-1.10.0/googlemock GTEST_ROOT=./gmock/googletest-release-1.10.0/googletest OS=LIN
    - name:  make tests 
      run : |
        make alltests TEST_SUITE=GMOCK GMOCK_ROOT=./gmock/googletest-release-1.10.0/googlemock GTEST_ROOT=./gmock/googletest-release-1.10.0/googletest OS=LIN
        make check OS=LIN
      
