name: Tests & Examples (WINDOWS)

on:
  push:
    branches: [ master ]
    paths-ignore:
    - 'README.md'
    - '.gitignore'
    - '.vscode/**'

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
    - name: make structure
      run: make structure OS=WIN
    - name: download gmock
      run: |
        mkdir -p ./gmock/
        curl https://codeload.github.com/google/googletest/zip/refs/tags/release-1.10.0 -o ./gmock/googletest-release-1.10.0.zip
        unzip ./gmock/googletest-release-1.10.0.zip -d ./gmock
        ls
    - name: install gmock
      run: |
        make install_gtest GTEST_ROOT=${{ github.workspace }}/gmock/googletest-release-1.10.0/googletest OS=LIN
        make install_gmock GMOCK_ROOT=${{ github.workspace }}/gmock/googletest-release-1.10.0/googlemock GTEST_ROOT=${{ github.workspace }}/gmock/googletest-release-1.10.0/googletest OS=LIN
    - name:  make tests 
      run : |
        make alltests TEST_SUITE=GMOCK GMOCK_ROOT=${{ github.workspace }}/gmock/googletest-release-1.10.0/googlemock GTEST_ROOT=${{ github.workspace }}/gmock/googletest-release-1.10.0/googletest OS=LIN
        make check OS=LIN
  examples:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
    - name: make structure
      run: make structure OS=WIN
    - name: make ping
      run: make ping OS=WIN
    - name: make keygen
      run: make keygen OS=WIN
      
